apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appdeployname }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.myimage.appcontainername }}
        image: "{{ .Values.myimage.myfullreponame }}"
        #image: "{{ .Values.myimage.reponame }}:{{ .Values.myimage.repotag }}"
        imagePullPolicy: {{ .Values.myimage.Whentopullimage }}
        ports:
        - containerPort: {{ .Values.myimage.containerandtargetPort }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-{{ .Values.myscret.myreposecretname }}